
# BRADBURY SAMPLING: Newfoundland

## Read in 2015 files
```{r}
bradesc2015 <- read.csv("C:/Users/keyserf/Documents/Data/Escape events and reports/Gillnetting2015 - Master Copy.csv")
bradsets2015 <- read.csv("C:/Users/keyserf/Documents/Data/Escape events and reports/Gillnetting2015 - Set Details.csv")
```

## Tidy up
```{r}
bradsets2015$Set.Time..UTC. <- dmy_hms(paste(bradsets2015$Date, bradsets2015$Set.Time..UTC.))
bradsets2015$Retrieval.Time..UTC. <- dmy_hms(paste(bradsets2015$Date, bradsets2015$Retrieval.Time..UTC.))
bradsets2015$duration <- bradsets2015$Retrieval.Time..UTC. - bradsets2015$Set.Time..UTC.

colnames(bradsets2015)[2] <- "River"

bradsets2015 <- dplyr::select(bradsets2015, Set.ID, River, Gear.Type, duration)

bradesc2015$River <- gsub("Du", "du", bradesc2015$River)
```

## Join metadata
```{r}
bradesc2015 <- join(bradesc2015, bradsets2015, type="left")
```

## Counts
```{r}
bradprops2015 <- ddply(.data=bradesc2015, .(Life.Stage, River, Gear.Type),
                       summarize,
                       count = length(unique(Sample.ID)))

bradprops2015$Esc <- c(1,1,1,1,2,2,2,2,2,2)

bradgill <- subset(bradprops2015, Gear.Type=="Gillnet")

bradrod <- subset(bradprops2015, Gear.Type=="Rod")

bradgill <- ddply(.data=bradgill, .(River, Gear.Type), 
                  summarize,
                  total=sum(count))

bradrod <- ddply(.data=bradrod, .(River, Gear.Type),
                 summarize,
                 total=sum(count))

bradtotals <- rbind(bradgill, bradrod)

bradprops2015 <- join(bradprops2015, bradtotals, type="left")

bradprops2015 <- subset(bradprops2015, Life.Stage=="Farmed")
add <- data.frame(Life.Stage=rep("Farmed", 2), 
                  River = c("Garnish River", "Little River"), 
                  Gear.Type=c("Gillnet", "Rod"), 
                  count=rep(0,2),
                  Esc=c(NA, NA),
                  total=rep(1,2))

bradprops2015 <- rbind(bradprops2015, add)

bradprops2015$prop <- bradprops2015$count/bradprops2015$total

write.csv(bradprops2015, "C:/Users/keyserf/Documents/Data/R output/bradprops2015.csv")

bradesc2015 <- subset(bradesc2015, Life.Stage=="Farmed")

bradesc2015$River <- as.factor(bradesc2015$River)

effort <- ddply(.data=bradsets2015, .(Gear.Type, River),
                summarize,
                time = sum(duration))


catch <- ddply(.data=bradesc2015, .(Gear.Type, River),
               summarize,
               catch=length(unique(Sample.ID)),
               lat = mean(Latitude..N.),
               long= mean(Longitude..E.))

CPUE <- join(effort, catch, type="left")

CPUE$adj.catch <- CPUE$catch/as.numeric(CPUE$time)

```

## Compare against propagule pressure
```{r}
prop.press_NL <- read.csv("C:/Users/keyserf/Documents/Data/R output/Propagule Pressure_NL_20142015_2016-12-15.csv")
plot(NL.low, xlim=c(-56, -55), ylim=c(47.5, 48))
text(CPUE$long, CPUE$lat)
CPUE$code <- as.factor(c("BDN", "GAR", "LTR", "SMB", "BDN", "LTR", "FBN"))

CPUEprop <- join(CPUE[,c(1,2,3,4,7,8)], prop.press_NL, type="left")

CPUEprop$catch[is.na(CPUEprop$catch)] <- 0
CPUEprop$time[is.na(CPUEprop$time)] <- 0
CPUEprop$adj.catch[is.na(CPUEprop$adj.catch)] <- 0

ggplot() + geom_point(data=CPUEprop, aes(log(prop.press), adj.catch)) +
  theme_classic() + ### favourite theme settings plus makes sure land is white
  theme(panel.background = element_blank(), panel.border=element_rect(colour="black", fill=NA))


bradprops2015$code <- c("BDN", "BDN", "FBN", "SMB", "GAR", "LTR")

bradprops2015 <- join(bradprops2015, prop.press_NL, type="left")

ggplot() + geom_point(data=bradprops2015, aes(prop.press, prop)) +
  theme_classic() + ### favourite theme settings plus makes sure land is white
  theme(panel.background = element_blank(), panel.border=element_rect(colour="black", fill=NA)) 

require(aod)
model1 <- glm(data=bradprops2015, prop ~ prop.press, family=binomial(link="probit"))
summary(model1)

newdata <- data.frame(prop.press=prop.press_q$prop.press, code=prop.press_NL$code)

newdata[, c("p", "se")] <- predict(model1, newdata,
  type = "response", se.fit=TRUE)[-3]

newdata

colnames(qsites)[1] <- "code"
names(newdata)

newdata <- join(qsites, newdata[], type="left")

ggplot() + geom_point(data=test, aes(prop.press, catch))

ggplot() + geom_point(data=test, aes(prop.press, time))

ggplot() + geom_point(data=test, aes(time, catch))

## try with propagule pressure for only 2014-2015


```

### Add in 2016 sampling
```{r}
brad2016 <- read.csv("C:/Users/keyserf/Documents/Data/Escape events and Reports/Bradbury sampling 2016.csv")
dev.off()
plot(ATLrast2, xlim=c(-56.3, -55), ylim=c(47.4,48.2))
text(sched$Long, sched$Lat, labels=sched$Number, col="red")
text(brad2016$Longitude[21:30], brad2016$Latitude__[21:30])


brad2016$Number <- c(47,47,48,48,37,27,25,29,38,29,
                           16, 47, 48, "NA", 16, 47, 48, "NA", 29, 19,
                           19,"NA",19,38, 29, 25, 37,38, 35, "NA", 
                           "NA", 29, 37,37,37,37,35,35,38,38,
                            38,25,27,27,25,25,25,40,40,25,
                           38,37,37,27,27,25,25,25,38,"NA",
                           29,29,"NA", "NA", 31,30,37)

brad2016 <- join(brad2016, sched, type="left")

brad2016[is.na(brad2016$Long)=="TRUE",11:10] <- rbind(c(47.688344, -55.124000),
                                                      c(47.688344, -55.124000),
                                                      c(47.569167, -55.731452),
                                                      c(47.569167, -55.731452),
                                                      c(47.569167, -55.731452),
                                                      c(47.65225, -55.93152),
                                                      c(47.569167, -55.731452),
                                                      c(47.569167, -55.731452))

brad2016$Name <- as.character(brad2016$Name)

brad2016[brad2016$Long==-55.124000,7] <- "Tickle Harbour"
brad2016[brad2016$Long==-55.731452,7] <- "Bill Skinners Cove"
brad2016[brad2016$Long==-55.93152,7] <- "Seal Nest Cove"


```

